-------------------------------------------------------------------------------------------------------------
-------------------------------------------- CREACION DE VISTAS ---------------------------------------------
-------------------------------------------------------------------------------------------------------------

-- VISTA PARA USUARIOS CON ROLES
CREATE OR REPLACE VIEW VM_USUARIOS_ROLES AS
SELECT
	U.ID_USUARIO,
	U.IDENTIFICACION,
	U.NOMBRE,
	U.APELLIDOS,
	U.CORREO,
	R.NOMBRE AS ROL,
	U.ESTADO
FROM
	TBL_USUARIOS U
JOIN
	TBL_ROLES R ON U.ID_ROL = R.ID_ROL;
	
-- VISTA PARA RESUMEN DE BENEFICIARIOS CON EDAD CALCULADA
CREATE OR REPLACE VIEW VM_BENEFICIARIOS_RESUMEN AS
SELECT
	B.ID_BENEFICIARIO,
	B.NOMBRE,
	B.APELLIDOS,
	B.GENERO,
	TRUNC(MONTHS_BETWEEN(SYSDATE, B.FECHA_NACIMIENTO)/12) AS EDAD,
	N.NOMBRE AS NIVEL
FROM
	TBL_BENEFICIARIOS B
LEFT JOIN
	TBL_NIVELES N ON B.ID_NIVEL = N.ID_NIVEL;

-- VISTA PARA BENEFICIARIOS CON NIVEL EDUCATIVO
CREATE OR REPLACE VIEW VM_BENEFICIARIOS_NIVEL AS
SELECT
	B.ID_BENEFICIARIO,
	B.IDENTIFICACION,
	B.NOMBRE,
	B.APELLIDOS,
	B.FECHA_NACIMIENTO,
	B.GENERO,
	B.DIRECCION,
	B.CONTACTO,
	B.CONDICION_ESPECIAL,
	B.PADECIMIENTOS,
	B.ALERGIAS,
	N.NOMBRE AS NIVEL
FROM
	TBL_BENEFICIARIOS B
LEFT JOIN
	TBL_NIVELES N ON B.ID_NIVEL = N.ID_NIVEL;

-- VISTA PARA ASIGNATURAS IMPARTIDAS POR PROFESOR Y NIVEL
CREATE OR REPLACE VIEW VM_ASIGNATURAS_PROFESOR_NIVEL AS
SELECT
	A.ID_ASIGNATURA,
	A.NOMBRE AS NOMBRE_ASIGNATURA,
	P.NOMBRE || ' ' || P.APELLIDOS AS PROFESOR,
	P.ESPECIALIDAD,
	N.NOMBRE AS NIVEL
FROM 
	TBL_ASIGNATURAS A
JOIN
	TBL_PROFESORES P ON A.ID_PROFESOR = P.ID_PROFESOR
JOIN
	TBL_NIVELES N ON A.ID_NIVEL = N.ID_NIVEL;
	
-- VISTA PARA ASIGNATURAS POR NIVEL
CREATE OR REPLACE VIEW VM_ASIGNATURAS_NIVEL AS
SELECT
	A.ID_ASIGNATURA,
	A.NOMBRE AS ASIGNATURA,
	N.NOMBRE AS NIVEL
FROM
	TBL_ASIGNATURAS A
JOIN
	TBL_NIVELES N ON A.ID_NIVEL = N.ID_NIVEL;

-- VISTA PARA PARTICIPACION DE BENEFICIARIOS EN EVENTOS
CREATE OR REPLACE VIEW VM_PARTICIPACION_EVENTOS AS
SELECT
	E.ID_EVENTO,
	E.NOMBRE AS NOMBRE_EVENTO,
	E.FECHA_INICIO,
	E.FECHA_FIN,
	B.ID_BENEFICIARIO,
	B.NOMBRE || ' ' || B.APELLIDOS AS NOMBRE_BENEFICIARIO
FROM
	TBL_PARTICIPACION_EVENTOS PE
JOIN
	TBL_EVENTOS E ON PE.ID_EVENTO = E.ID_EVENTO
JOIN
	TBL_BENEFICIARIOS B ON PE.ID_BENEFICIARIO = B.ID_BENEFICIARIO;
	
-- VISTA PARA MATERIALES POR ASIGNATURA
CREATE OR REPLACE VIEW VM_MATERIALES_ASIGNATURA AS
SELECT
	M.ID_MATERIAL,
	M.NOMBRE AS NOMBRE_MATERIAL,
	M.TIPO,
	M.CANTIDAD,
	M.ESTADO,
	A.NOMBRE AS ASIGNATURA
FROM 
	TBL_MATERIALES M
LEFT JOIN
	TBL_ASIGNATURAS A ON M.ID_ASIGNATURA = A.ID_ASIGNATURA;
	
-- VISTA PARA BITACORA DE ACCIONES DE USUARIOS
CREATE OR REPLACE VIEW VM_BITACORA_ACCIONES AS
SELECT
	B.ID_BITACORA,
	B.FECHA_HORA,
	B.ACCION,
	U.ID_USUARIO,
	U.NOMBRE || ' ' || U.APELLIDOS AS USUARIO
FROM
	TBL_BITACORAS B
JOIN
	TBL_USUARIOS U ON B.ID_USUARIO = U.ID_USUARIO;
	
-- VISTA PARA ERRORES DE SISTEMA REGISTRADOS
CREATE OR REPLACE VIEW VM_AUDITORIA_ERRORES AS
SELECT
	AE.ID_ERROR,
	AE.FECHA_HORA,
	AE.MENSAJE,
	AE.ORIGEN,
	U.NOMBRE || ' ' || U.APELLIDOS AS USUARIO
FROM
	TBL_AUDITORIA_ERRORES AE
LEFT JOIN
	TBL_USUARIOS U ON AE.ID_USUARIO = U.ID_USUARIO;
	