CREATE OR REPLACE VIEW VM_ASIGNATURAS_PROFESOR_NIVEL AS
SELECT
	A.ID_ASIGNATURA,
	A.NOMBRE AS NOMBRE_ASIGNATURA,
	P.NOMBRE || ' ' || P.APELLIDOS AS PROFESOR,
	P.ESPECIALIDAD,
	N.NOMBRE AS NIVEL
FROM 
	TBL_ASIGNATURAS A
JOIN
	TBL_PROFESORES P ON A.ID_PROFESOR = P.ID_PROFESOR
JOIN
	TBL_NIVELES N ON A.ID_NIVEL = N.ID_NIVEL;
	