CREATE OR REPLACE VIEW VM_AUDITORIA_ERRORES AS
SELECT
	AE.ID_ERROR,
	AE.FECHA_HORA,
	AE.MENSAJE,
	AE.ORIGEN,
	U.NOMBRE || ' ' || U.APELLIDOS AS USUARIO
FROM
	TBL_AUDITORIA_ERRORES AE
LEFT JOIN
	TBL_USUARIOS U ON AE.ID_USUARIO = U.ID_USUARIO;
	