CREATE OR REPLACE VIEW VM_BENEFICIARIOS_RESUMEN AS
SELECT
	B.ID_BENEFICIARIO,
	B.NOMBRE,
	B.APELLIDOS,
	B.GENERO,
	TRUNC(MONTHS_BETWEEN(SYSDATE, B.FECHA_NACIMIENTO)/12) AS EDAD,
	N.NOMBRE AS NIVEL
FROM
	TBL_BENEFICIARIOS B
LEFT JOIN
	TBL_NIVELES N ON B.ID_NIVEL = N.ID_NIVEL;
	