CREATE OR REPLACE VIEW VM_BITACORA_ACCIONES AS
SELECT
	B.ID_BITACORA,
	B.FECHA_HORA,
	B.ACCION,
	U.ID_USUARIO,
	U.NOMBRE || ' ' || U.APELLIDOS AS USUARIO
FROM
	TBL_BITACORAS B
JOIN
	TBL_USUARIOS U ON B.ID_USUARIO = U.ID_USUARIO;
	