CREATE OR REPLACE VIEW VM_BENEFICIARIOS_NIVEL AS
SELECT
	B.ID_BENEFICIARIO,
	B.IDENTIFICACION,
	B.NOMBRE,
	B.APELLIDOS,
	B.FECHA_NACIMIENTO,
	B.GENERO,
	B.DIRECCION,
	B.CONTACTO,
	B.CONDICION_ESPECIAL,
	B.PADECIMIENTOS,
	B.ALERGIAS,
	N.NOMBRE AS NIVEL
FROM
	TBL_BENEFICIARIOS B
LEFT JOIN
	TBL_NIVELES N ON B.ID_NIVEL = N.ID_NIVEL;
	