CREATE OR REPLACE VIEW VM_MATERIALES_ASIGNATURA AS
SELECT
	M.ID_MATERIAL,
	M.NOMBRE AS NOMBRE_MATERIAL,
	M.TIPO,
	M.CANTIDAD,
	M.ESTADO,
	A.NOMBRE AS ASIGNATURA
FROM 
	TBL_MATERIALES M
LEFT JOIN
	TBL_ASIGNATURAS A ON M.ID_ASIGNATURA = A.ID_ASIGNATURA;
	