CREATE OR REPLACE VIEW VM_PARTICIPACION_EVENTOS AS
SELECT
	E.ID_EVENTO,
	E.NOMBRE AS NOMBRE_EVENTO,
	E.FECHA_INICIO,
	E.FECHA_FIN,
	B.ID_BENEFICIARIO,
	B.NOMBRE || ' ' || B.APELLIDOS AS NOMBRE_BENEFICIARIO
FROM
	TBL_PARTICIPACION_EVENTOS PE
JOIN
	TBL_EVENTOS E ON PE.ID_EVENTO = E.ID_EVENTO
JOIN
	TBL_BENEFICIARIOS B ON PE.ID_BENEFICIARIO = B.ID_BENEFICIARIO;
	