CREATE OR REPLACE VIEW VM_USUARIOS_ROLES AS
SELECT
	U.ID_USUARIO,
	U.IDENTIFICACION,
	U.NOMBRE,
	U.APELLIDOS,
	U.CORREO,
	R.NOMBRE AS ROL,
	U.ESTADO
FROM
	TBL_USUARIOS U
JOIN
	TBL_ROLES R ON U.ID_ROL = R.ID_ROL;
	