CREATE OR REPLACE PACKAGE PKG_PROCEDIMIENTOS AS
	PROCEDURE SP_AGREGAR_USUARIO(
        P_IDENTIFICACION IN VARCHAR2,
        P_NOMBRE IN VARCHAR2,
        P_APELLIDOS IN VARCHAR2,
        P_CORREO IN VARCHAR2,
        P_CONTRASENNA IN VARCHAR2,
        P_ID_ROL IN NUMBER
    );

    PROCEDURE SP_ACTUALIZAR_ESTADO_USUARIO(
        P_ID_USUARIO IN NUMBER,
        P_ESTADO IN NUMBER
    );

    PROCEDURE SP_LISTAR_BENEFICIARIOS_NIVEL(
        P_ID_NIVEL IN NUMBER
    );

    PROCEDURE SP_LISTAR_PROFESORES_CON_TITULOS(
        P_MIN_TITULOS IN NUMBER
    );

    PROCEDURE SP_INSERTAR_EVENTO(
        P_NOMBRE IN VARCHAR2,
        P_FECHA_INICIO IN DATE,
        P_FECHA_FIN IN DATE,
        P_DESCRIPCION IN VARCHAR2,
        P_RUTA_IMAGEN IN VARCHAR2
    );

    PROCEDURE SP_REGISTRAR_PARTICIPACION(
        P_ID_EVENTO IN NUMBER,
        P_ID_BENEFICIARIO IN NUMBER
    );

    PROCEDURE SP_ELIMINAR_PARTICIPACION_EVENTO(
        P_ID_EVENTO IN NUMBER,
        P_ID_BENEFICIARIO IN NUMBER
    );

    PROCEDURE SP_LISTAR_MATERIALES_ASIGNATURA(
        P_ID_ASIGNATURA IN NUMBER
    );

    PROCEDURE SP_VER_BITACORA_USUARIOS;

    PROCEDURE SP_REGISTRAR_ERROR(
        P_MENSAJE IN VARCHAR2,
        P_ORIGEN IN VARCHAR2,
        P_ID_USUARIO IN NUMBER
    );
END PKG_PROCEDIMIENTOS;

CREATE OR REPLACE PACKAGE BODY PKG_PROCEDIMIENTOS AS

	PROCEDURE SP_AGREGAR_USUARIO(
        P_IDENTIFICACION IN VARCHAR2,
        P_NOMBRE IN VARCHAR2,
        P_APELLIDOS IN VARCHAR2,
        P_CORREO IN VARCHAR2,
        P_CONTRASENNA IN VARCHAR2,
        P_ID_ROL IN NUMBER
    ) AS
    BEGIN
        INSERT INTO TBL_USUARIOS (
            IDENTIFICACION, NOMBRE, APELLIDOS, CORREO, CONTRASENNA, ESTADO, ID_ROL
        )
        VALUES (
            P_IDENTIFICACION, P_NOMBRE, P_APELLIDOS, P_CORREO, P_CONTRASENNA, 1, P_ID_ROL
        );
    END;

    PROCEDURE SP_ACTUALIZAR_ESTADO_USUARIO(
        P_ID_USUARIO IN NUMBER,
        P_ESTADO IN NUMBER
    ) AS
    BEGIN
        UPDATE TBL_USUARIOS
        SET ESTADO = P_ESTADO
        WHERE ID_USUARIO = P_ID_USUARIO;
    END;

    PROCEDURE SP_LISTAR_BENEFICIARIOS_NIVEL(
        P_ID_NIVEL IN NUMBER
    ) AS
        CURSOR C_BENEFICIARIO IS
            SELECT NOMBRE, APELLIDOS, IDENTIFICACION
            FROM TBL_BENEFICIARIOS
            WHERE ID_NIVEL = P_ID_NIVEL;
        V_NOMBRE TBL_BENEFICIARIOS.NOMBRE%TYPE;
        V_APELLIDOS TBL_BENEFICIARIOS.APELLIDOS%TYPE;
        V_IDENTIFICACION TBL_BENEFICIARIOS.IDENTIFICACION%TYPE;
    BEGIN
        OPEN C_BENEFICIARIO;
        LOOP
            FETCH C_BENEFICIARIO INTO V_NOMBRE, V_APELLIDOS, V_IDENTIFICACION;
            EXIT WHEN C_BENEFICIARIO%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Beneficiario: ' || V_NOMBRE || ' ' || V_APELLIDOS || ' - ID: ' || V_IDENTIFICACION);
        END LOOP;
        CLOSE C_BENEFICIARIO;
    END;

    PROCEDURE SP_LISTAR_PROFESORES_CON_TITULOS(
        P_MIN_TITULOS IN NUMBER
    ) AS
        CURSOR C_PROFESOR IS
            SELECT NOMBRE, APELLIDOS, CANTIDAD_TITULOS
            FROM TBL_PROFESORES
            WHERE CANTIDAD_TITULOS >= P_MIN_TITULOS;
        V_NOMBRE TBL_PROFESORES.NOMBRE%TYPE;
        V_APELLIDOS TBL_PROFESORES.APELLIDOS%TYPE;
        V_TITULOS TBL_PROFESORES.CANTIDAD_TITULOS%TYPE;
    BEGIN
        OPEN C_PROFESOR;
        LOOP
            FETCH C_PROFESOR INTO V_NOMBRE, V_APELLIDOS, V_TITULOS;
            EXIT WHEN C_PROFESOR%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Profesor: ' || V_NOMBRE || ' ' || V_APELLIDOS || ' | Titulos: ' || V_TITULOS);
        END LOOP;
        CLOSE C_PROFESOR;
    END;

    PROCEDURE SP_INSERTAR_EVENTO(
        P_NOMBRE IN VARCHAR2,
        P_FECHA_INICIO IN DATE,
        P_FECHA_FIN IN DATE,
        P_DESCRIPCION IN VARCHAR2,
        P_RUTA_IMAGEN IN VARCHAR2
    ) AS
    BEGIN
        INSERT INTO TBL_EVENTOS (NOMBRE, FECHA_INICIO, FECHA_FIN, DESCRIPCION, RUTA_IMAGEN)
        VALUES (P_NOMBRE, P_FECHA_INICIO, P_FECHA_FIN, P_DESCRIPCION, P_RUTA_IMAGEN);
    END;

    PROCEDURE SP_REGISTRAR_PARTICIPACION(
        P_ID_EVENTO IN NUMBER,
        P_ID_BENEFICIARIO IN NUMBER
    ) AS
    BEGIN
        INSERT INTO TBL_PARTICIPACION_EVENTOS (ID_EVENTO, ID_BENEFICIARIO)
        VALUES (P_ID_EVENTO, P_ID_BENEFICIARIO);
    END;

    PROCEDURE SP_ELIMINAR_PARTICIPACION_EVENTO(
        P_ID_EVENTO IN NUMBER,
        P_ID_BENEFICIARIO IN NUMBER
    ) AS
    BEGIN
        DELETE FROM TBL_PARTICIPACION_EVENTOS
        WHERE ID_EVENTO = P_ID_EVENTO AND ID_BENEFICIARIO = P_ID_BENEFICIARIO;
    END;

    PROCEDURE SP_LISTAR_MATERIALES_ASIGNATURA(
        P_ID_ASIGNATURA IN NUMBER
    ) AS
        CURSOR C_MATERIAL IS
            SELECT NOMBRE, TIPO, CANTIDAD, ESTADO
            FROM TBL_MATERIALES
            WHERE ID_ASIGNATURA = P_ID_ASIGNATURA;
        V_NOMBRE TBL_MATERIALES.NOMBRE%TYPE;
        V_TIPO TBL_MATERIALES.TIPO%TYPE;
        V_CANTIDAD TBL_MATERIALES.CANTIDAD%TYPE;
        V_ESTADO TBL_MATERIALES.ESTADO%TYPE;
    BEGIN
        OPEN C_MATERIAL;
        LOOP
            FETCH C_MATERIAL INTO V_NOMBRE, V_TIPO, V_CANTIDAD, V_ESTADO;
            EXIT WHEN C_MATERIAL%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Material: ' || V_NOMBRE || ' | Tipo: ' || V_TIPO || ' | Cantidad: ' || V_CANTIDAD || ' | Estado: ' || V_ESTADO);
        END LOOP;
        CLOSE C_MATERIAL;
    END;

    PROCEDURE SP_VER_BITACORA_USUARIOS IS
        V_ROW TBL_BITACORAS%ROWTYPE;
        CURSOR C_BITACORA IS SELECT * FROM TBL_BITACORAS;
    BEGIN
        OPEN C_BITACORA;
        LOOP
            FETCH C_BITACORA INTO V_ROW;
            EXIT WHEN C_BITACORA%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('[' || V_ROW.FECHA_HORA || '] Usuario: ' || V_ROW.ID_USUARIO || ' realizo una accion: ' || V_ROW.ACCION);
        END LOOP;
        CLOSE C_BITACORA;
    END;

    PROCEDURE SP_REGISTRAR_ERROR(
        P_MENSAJE IN VARCHAR2,
        P_ORIGEN IN VARCHAR2,
        P_ID_USUARIO IN NUMBER
    ) AS
    BEGIN
        INSERT INTO TBL_AUDITORIA_ERRORES (MENSAJE, ORIGEN, ID_USUARIO)
        VALUES (P_MENSAJE, P_ORIGEN, P_ID_USUARIO);
    END;
	
END PKG_PROCEDIMIENTOS;