CREATE OR REPLACE PACKAGE PKG_SECUENCIAS AS
	FUNCTION NEXT_ROL RETURN NUMBER;
	FUNCTION NEXT_USUARIO RETURN NUMBER;
	FUNCTION NEXT_BENEFICIARIO RETURN NUMBER;
	FUNCTION NEXT_PROFESOR RETURN NUMBER;
	FUNCTION NEXT_NIVEL RETURN NUMBER;
	FUNCTION NEXT_ASIGNATURA RETURN NUMBER;
	FUNCTION NEXT_MATERIAL RETURN NUMBER;
	FUNCTION NEXT_EVENTO RETURN NUMBER;
	FUNCTION NEXT_BITACORA RETURN NUMBER;
	FUNCTION NEXT_ERROR RETURN NUMBER;
END PKG_SECUENCIAS;

CREATE OR REPLACE PACKAGE BODY PKG_SECUENCIAS AS

	FUNCTION NEXT_ROL RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_ROLES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_USUARIO RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_USUARIOS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_BENEFICIARIO RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_BENEFICIARIOS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_PROFESOR RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_PROFESORES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_NIVEL RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_NIVELES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_ASIGNATURA RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_ASIGNATURAS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_MATERIAL RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_MATERIALES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_EVENTO RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_EVENTOS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_BITACORA RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_BITACORAS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_ERROR RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_AUDITORIA_ERRORES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
END PKG_SECUENCIAS;
