CREATE OR REPLACE PACKAGE PKG_VISTAS AS
	FUNCTION GET_USUARIOS_ROLES RETURN SYS_REFCURSOR;
	FUNCTION GET_BENEFICIARIOS_RESUMEN RETURN SYS_REFCURSOR;
	FUNCTION GET_BENEFICIARIOS_NIVEL RETURN SYS_REFCURSOR;
	FUNCTION GET_ASIGNATURAS_PROFESOR_NIVEL RETURN SYS_REFCURSOR;
	FUNCTION GET_ASIGNATURAS_NIVEL RETURN SYS_REFCURSOR;
	FUNCTION GET_PARTICIPACION_EVENTOS RETURN SYS_REFCURSOR;
	FUNCTION GET_MATERIALES_ASIGNATURA RETURN SYS_REFCURSOR;
	FUNCTION GET_BITACORA_ACCIONES RETURN SYS_REFCURSOR;
	FUNCTION GET_AUDITORIA_ERRORES RETURN SYS_REFCURSOR;
END PKG_VISTAS;

CREATE OR REPLACE PACKAGE BODY PKG_VISTAS AS

	FUNCTION GET_USUARIOS_ROLES RETURN SYS_REFCURSOR IS
		C_USUARIOS SYS_REFCURSOR;
	BEGIN
		OPEN C_USUARIOS FOR
		SELECT * FROM VM_USUARIOS_ROLES;
		RETURN C_USUARIOS;
	END;
	
	FUNCTION GET_BENEFICIARIOS_RESUMEN RETURN SYS_REFCURSOR IS
		C_RESUMEN SYS_REFCURSOR;
	BEGIN
		OPEN C_RESUMEN FOR
		SELECT * FROM VM_BENEFICIARIOS_RESUMEN;
		RETURN C_RESUMEN;
	END;
	
	FUNCTION GET_BENEFICIARIOS_NIVEL RETURN SYS_REFCURSOR IS
		C_BENEF_NIVEL SYS_REFCURSOR;
	BEGIN
		OPEN C_BENEF_NIVEL FOR
		SELECT * FROM VM_BENEFICIARIOS_NIVEL;
		RETURN C_BENEF_NIVEL;
	END;
	
	FUNCTION GET_ASIGNATURAS_PROFESOR_NIVEL RETURN SYS_REFCURSOR IS
		C_ASIGNATURAS SYS_REFCURSOR;
	BEGIN
		OPEN C_ASIGNATURAS FOR
		SELECT * FROM VM_ASIGNATURAS_PROFESOR_NIVEL;
		RETURN C_ASIGNATURAS;
	END;
	
	FUNCTION GET_ASIGNATURAS_NIVEL RETURN SYS_REFCURSOR IS
		C_ASIGN_NIVEL SYS_REFCURSOR;
	BEGIN
		OPEN C_ASIGN_NIVEL FOR
		SELECT * FROM VM_ASIGNATURAS_NIVEL;
		RETURN C_ASIGN_NIVEL;
	END;
	
	FUNCTION GET_PARTICIPACION_EVENTOS RETURN SYS_REFCURSOR IS
		C_EVENTOS SYS_REFCURSOR;
	BEGIN
		OPEN C_EVENTOS FOR
		SELECT * FROM VM_PARTICIPACION_EVENTOS;
		RETURN C_EVENTOS;
	END;
	
	FUNCTION GET_MATERIALES_ASIGNATURA RETURN SYS_REFCURSOR IS
		C_MATERIALES SYS_REFCURSOR;
	BEGIN
		OPEN C_MATERIALES FOR
		SELECT * FROM VM_MATERIALES_ASIGNATURA;
		RETURN C_MATERIALES;
	END;
	
	FUNCTION GET_BITACORA_ACCIONES RETURN SYS_REFCURSOR IS
		C_BITACORA SYS_REFCURSOR;
	BEGIN
		OPEN C_BITACORA FOR
		SELECT * FROM VM_BITACORA_ACCIONES;
		RETURN C_BITACORA;
	END;
	
	FUNCTION GET_AUDITORIA_ERRORES RETURN SYS_REFCURSOR IS
		C_ERRORES_AUDIT SYS_REFCURSOR;
	BEGIN
		OPEN C_ERRORES_AUDIT FOR
		SELECT * FROM VM_AUDITORIA_ERRORES;
		RETURN C_ERRORES_AUDIT;
	END;
	
END PKG_VISTAS;
