---------------------------------------------------------------------------------------------------------------
-------------------------------------------- CREACION DE PAQUETES ---------------------------------------------
---------------------------------------------------------------------------------------------------------------

-- PAQUETE PARA ALMACENAR SECUENCIAS
CREATE OR REPLACE PACKAGE PKG_SECUENCIAS AS
	FUNCTION NEXT_ROL RETURN NUMBER;
	FUNCTION NEXT_USUARIO RETURN NUMBER;
	FUNCTION NEXT_BENEFICIARIO RETURN NUMBER;
	FUNCTION NEXT_PROFESOR RETURN NUMBER;
	FUNCTION NEXT_NIVEL RETURN NUMBER;
	FUNCTION NEXT_ASIGNATURA RETURN NUMBER;
	FUNCTION NEXT_MATERIAL RETURN NUMBER;
	FUNCTION NEXT_EVENTO RETURN NUMBER;
	FUNCTION NEXT_BITACORA RETURN NUMBER;
	FUNCTION NEXT_ERROR RETURN NUMBER;
END PKG_SECUENCIAS;

CREATE OR REPLACE PACKAGE BODY PKG_SECUENCIAS AS

	FUNCTION NEXT_ROL RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_ROLES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_USUARIO RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_USUARIOS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_BENEFICIARIO RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_BENEFICIARIOS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_PROFESOR RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_PROFESORES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_NIVEL RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_NIVELES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_ASIGNATURA RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_ASIGNATURAS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_MATERIAL RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_MATERIALES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_EVENTO RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_EVENTOS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_BITACORA RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_BITACORAS.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
	FUNCTION NEXT_ERROR RETURN NUMBER IS
		V_NEXT NUMBER;
	BEGIN
		SELECT SEQ_AUDITORIA_ERRORES.NEXTVAL INTO V_NEXT FROM DUAL;
		RETURN V_NEXT;
	END;
	
END PKG_SECUENCIAS;

-- PAQUETE PARA ALMACENAR VISTAS
CREATE OR REPLACE PACKAGE PKG_VISTAS AS
	FUNCTION GET_USUARIOS_ROLES RETURN SYS_REFCURSOR;
	FUNCTION GET_BENEFICIARIOS_RESUMEN RETURN SYS_REFCURSOR;
	FUNCTION GET_BENEFICIARIOS_NIVEL RETURN SYS_REFCURSOR;
	FUNCTION GET_ASIGNATURAS_PROFESOR_NIVEL RETURN SYS_REFCURSOR;
	FUNCTION GET_ASIGNATURAS_NIVEL RETURN SYS_REFCURSOR;
	FUNCTION GET_PARTICIPACION_EVENTOS RETURN SYS_REFCURSOR;
	FUNCTION GET_MATERIALES_ASIGNATURA RETURN SYS_REFCURSOR;
	FUNCTION GET_BITACORA_ACCIONES RETURN SYS_REFCURSOR;
	FUNCTION GET_AUDITORIA_ERRORES RETURN SYS_REFCURSOR;
END PKG_VISTAS;

CREATE OR REPLACE PACKAGE BODY PKG_VISTAS AS

	FUNCTION GET_USUARIOS_ROLES RETURN SYS_REFCURSOR IS
		C_USUARIOS SYS_REFCURSOR;
	BEGIN
		OPEN C_USUARIOS FOR
		SELECT * FROM VM_USUARIOS_ROLES;
		RETURN C_USUARIOS;
	END;
	
	FUNCTION GET_BENEFICIARIOS_RESUMEN RETURN SYS_REFCURSOR IS
		C_RESUMEN SYS_REFCURSOR;
	BEGIN
		OPEN C_RESUMEN FOR
		SELECT * FROM VM_BENEFICIARIOS_RESUMEN;
		RETURN C_RESUMEN;
	END;
	
	FUNCTION GET_BENEFICIARIOS_NIVEL RETURN SYS_REFCURSOR IS
		C_BENEF_NIVEL SYS_REFCURSOR;
	BEGIN
		OPEN C_BENEF_NIVEL FOR
		SELECT * FROM VM_BENEFICIARIOS_NIVEL;
		RETURN C_BENEF_NIVEL;
	END;
	
	FUNCTION GET_ASIGNATURAS_PROFESOR_NIVEL RETURN SYS_REFCURSOR IS
		C_ASIGNATURAS SYS_REFCURSOR;
	BEGIN
		OPEN C_ASIGNATURAS FOR
		SELECT * FROM VM_ASIGNATURAS_PROFESOR_NIVEL;
		RETURN C_ASIGNATURAS;
	END;
	
	FUNCTION GET_ASIGNATURAS_NIVEL RETURN SYS_REFCURSOR IS
		C_ASIGN_NIVEL SYS_REFCURSOR;
	BEGIN
		OPEN C_ASIGN_NIVEL FOR
		SELECT * FROM VM_ASIGNATURAS_NIVEL;
		RETURN C_ASIGN_NIVEL;
	END;
	
	FUNCTION GET_PARTICIPACION_EVENTOS RETURN SYS_REFCURSOR IS
		C_EVENTOS SYS_REFCURSOR;
	BEGIN
		OPEN C_EVENTOS FOR
		SELECT * FROM VM_PARTICIPACION_EVENTOS;
		RETURN C_EVENTOS;
	END;
	
	FUNCTION GET_MATERIALES_ASIGNATURA RETURN SYS_REFCURSOR IS
		C_MATERIALES SYS_REFCURSOR;
	BEGIN
		OPEN C_MATERIALES FOR
		SELECT * FROM VM_MATERIALES_ASIGNATURA;
		RETURN C_MATERIALES;
	END;
	
	FUNCTION GET_BITACORA_ACCIONES RETURN SYS_REFCURSOR IS
		C_BITACORA SYS_REFCURSOR;
	BEGIN
		OPEN C_BITACORA FOR
		SELECT * FROM VM_BITACORA_ACCIONES;
		RETURN C_BITACORA;
	END;
	
	FUNCTION GET_AUDITORIA_ERRORES RETURN SYS_REFCURSOR IS
		C_ERRORES_AUDIT SYS_REFCURSOR;
	BEGIN
		OPEN C_ERRORES_AUDIT FOR
		SELECT * FROM VM_AUDITORIA_ERRORES;
		RETURN C_ERRORES_AUDIT;
	END;
	
END PKG_VISTAS;

-- PAQUETE PARA ALMACENAR PROCEDIMIENTOS
CREATE OR REPLACE PACKAGE PKG_PROCEDIMIENTOS AS
	PROCEDURE SP_AGREGAR_USUARIO(
        P_IDENTIFICACION IN VARCHAR2,
        P_NOMBRE IN VARCHAR2,
        P_APELLIDOS IN VARCHAR2,
        P_CORREO IN VARCHAR2,
        P_CONTRASENNA IN VARCHAR2,
        P_ID_ROL IN NUMBER
    );

    PROCEDURE SP_ACTUALIZAR_ESTADO_USUARIO(
        P_ID_USUARIO IN NUMBER,
        P_ESTADO IN NUMBER
    );

    PROCEDURE SP_LISTAR_BENEFICIARIOS_NIVEL(
        P_ID_NIVEL IN NUMBER
    );

    PROCEDURE SP_LISTAR_PROFESORES_CON_TITULOS(
        P_MIN_TITULOS IN NUMBER
    );

    PROCEDURE SP_INSERTAR_EVENTO(
        P_NOMBRE IN VARCHAR2,
        P_FECHA_INICIO IN DATE,
        P_FECHA_FIN IN DATE,
        P_DESCRIPCION IN VARCHAR2,
        P_RUTA_IMAGEN IN VARCHAR2
    );

    PROCEDURE SP_REGISTRAR_PARTICIPACION(
        P_ID_EVENTO IN NUMBER,
        P_ID_BENEFICIARIO IN NUMBER
    );

    PROCEDURE SP_ELIMINAR_PARTICIPACION_EVENTO(
        P_ID_EVENTO IN NUMBER,
        P_ID_BENEFICIARIO IN NUMBER
    );

    PROCEDURE SP_LISTAR_MATERIALES_ASIGNATURA(
        P_ID_ASIGNATURA IN NUMBER
    );

    PROCEDURE SP_VER_BITACORA_USUARIOS;

    PROCEDURE SP_REGISTRAR_ERROR(
        P_MENSAJE IN VARCHAR2,
        P_ORIGEN IN VARCHAR2,
        P_ID_USUARIO IN NUMBER
    );
END PKG_PROCEDIMIENTOS;

CREATE OR REPLACE PACKAGE BODY PKG_PROCEDIMIENTOS AS

	PROCEDURE SP_AGREGAR_USUARIO(
        P_IDENTIFICACION IN VARCHAR2,
        P_NOMBRE IN VARCHAR2,
        P_APELLIDOS IN VARCHAR2,
        P_CORREO IN VARCHAR2,
        P_CONTRASENNA IN VARCHAR2,
        P_ID_ROL IN NUMBER
    ) AS
    BEGIN
        INSERT INTO TBL_USUARIOS (
            IDENTIFICACION, NOMBRE, APELLIDOS, CORREO, CONTRASENNA, ESTADO, ID_ROL
        )
        VALUES (
            P_IDENTIFICACION, P_NOMBRE, P_APELLIDOS, P_CORREO, P_CONTRASENNA, 1, P_ID_ROL
        );
    END;

    PROCEDURE SP_ACTUALIZAR_ESTADO_USUARIO(
        P_ID_USUARIO IN NUMBER,
        P_ESTADO IN NUMBER
    ) AS
    BEGIN
        UPDATE TBL_USUARIOS
        SET ESTADO = P_ESTADO
        WHERE ID_USUARIO = P_ID_USUARIO;
    END;

    PROCEDURE SP_LISTAR_BENEFICIARIOS_NIVEL(
        P_ID_NIVEL IN NUMBER
    ) AS
        CURSOR C_BENEFICIARIO IS
            SELECT NOMBRE, APELLIDOS, IDENTIFICACION
            FROM TBL_BENEFICIARIOS
            WHERE ID_NIVEL = P_ID_NIVEL;
        V_NOMBRE TBL_BENEFICIARIOS.NOMBRE%TYPE;
        V_APELLIDOS TBL_BENEFICIARIOS.APELLIDOS%TYPE;
        V_IDENTIFICACION TBL_BENEFICIARIOS.IDENTIFICACION%TYPE;
    BEGIN
        OPEN C_BENEFICIARIO;
        LOOP
            FETCH C_BENEFICIARIO INTO V_NOMBRE, V_APELLIDOS, V_IDENTIFICACION;
            EXIT WHEN C_BENEFICIARIO%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Beneficiario: ' || V_NOMBRE || ' ' || V_APELLIDOS || ' - ID: ' || V_IDENTIFICACION);
        END LOOP;
        CLOSE C_BENEFICIARIO;
    END;

    PROCEDURE SP_LISTAR_PROFESORES_CON_TITULOS(
        P_MIN_TITULOS IN NUMBER
    ) AS
        CURSOR C_PROFESOR IS
            SELECT NOMBRE, APELLIDOS, CANTIDAD_TITULOS
            FROM TBL_PROFESORES
            WHERE CANTIDAD_TITULOS >= P_MIN_TITULOS;
        V_NOMBRE TBL_PROFESORES.NOMBRE%TYPE;
        V_APELLIDOS TBL_PROFESORES.APELLIDOS%TYPE;
        V_TITULOS TBL_PROFESORES.CANTIDAD_TITULOS%TYPE;
    BEGIN
        OPEN C_PROFESOR;
        LOOP
            FETCH C_PROFESOR INTO V_NOMBRE, V_APELLIDOS, V_TITULOS;
            EXIT WHEN C_PROFESOR%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Profesor: ' || V_NOMBRE || ' ' || V_APELLIDOS || ' | Titulos: ' || V_TITULOS);
        END LOOP;
        CLOSE C_PROFESOR;
    END;

    PROCEDURE SP_INSERTAR_EVENTO(
        P_NOMBRE IN VARCHAR2,
        P_FECHA_INICIO IN DATE,
        P_FECHA_FIN IN DATE,
        P_DESCRIPCION IN VARCHAR2,
        P_RUTA_IMAGEN IN VARCHAR2
    ) AS
    BEGIN
        INSERT INTO TBL_EVENTOS (NOMBRE, FECHA_INICIO, FECHA_FIN, DESCRIPCION, RUTA_IMAGEN)
        VALUES (P_NOMBRE, P_FECHA_INICIO, P_FECHA_FIN, P_DESCRIPCION, P_RUTA_IMAGEN);
    END;

    PROCEDURE SP_REGISTRAR_PARTICIPACION(
        P_ID_EVENTO IN NUMBER,
        P_ID_BENEFICIARIO IN NUMBER
    ) AS
    BEGIN
        INSERT INTO TBL_PARTICIPACION_EVENTOS (ID_EVENTO, ID_BENEFICIARIO)
        VALUES (P_ID_EVENTO, P_ID_BENEFICIARIO);
    END;

    PROCEDURE SP_ELIMINAR_PARTICIPACION_EVENTO(
        P_ID_EVENTO IN NUMBER,
        P_ID_BENEFICIARIO IN NUMBER
    ) AS
    BEGIN
        DELETE FROM TBL_PARTICIPACION_EVENTOS
        WHERE ID_EVENTO = P_ID_EVENTO AND ID_BENEFICIARIO = P_ID_BENEFICIARIO;
    END;

    PROCEDURE SP_LISTAR_MATERIALES_ASIGNATURA(
        P_ID_ASIGNATURA IN NUMBER
    ) AS
        CURSOR C_MATERIAL IS
            SELECT NOMBRE, TIPO, CANTIDAD, ESTADO
            FROM TBL_MATERIALES
            WHERE ID_ASIGNATURA = P_ID_ASIGNATURA;
        V_NOMBRE TBL_MATERIALES.NOMBRE%TYPE;
        V_TIPO TBL_MATERIALES.TIPO%TYPE;
        V_CANTIDAD TBL_MATERIALES.CANTIDAD%TYPE;
        V_ESTADO TBL_MATERIALES.ESTADO%TYPE;
    BEGIN
        OPEN C_MATERIAL;
        LOOP
            FETCH C_MATERIAL INTO V_NOMBRE, V_TIPO, V_CANTIDAD, V_ESTADO;
            EXIT WHEN C_MATERIAL%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Material: ' || V_NOMBRE || ' | Tipo: ' || V_TIPO || ' | Cantidad: ' || V_CANTIDAD || ' | Estado: ' || V_ESTADO);
        END LOOP;
        CLOSE C_MATERIAL;
    END;

    PROCEDURE SP_VER_BITACORA_USUARIOS IS
        V_ROW TBL_BITACORAS%ROWTYPE;
        CURSOR C_BITACORA IS SELECT * FROM TBL_BITACORAS;
    BEGIN
        OPEN C_BITACORA;
        LOOP
            FETCH C_BITACORA INTO V_ROW;
            EXIT WHEN C_BITACORA%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('[' || V_ROW.FECHA_HORA || '] Usuario: ' || V_ROW.ID_USUARIO || ' realizo una accion: ' || V_ROW.ACCION);
        END LOOP;
        CLOSE C_BITACORA;
    END;

    PROCEDURE SP_REGISTRAR_ERROR(
        P_MENSAJE IN VARCHAR2,
        P_ORIGEN IN VARCHAR2,
        P_ID_USUARIO IN NUMBER
    ) AS
    BEGIN
        INSERT INTO TBL_AUDITORIA_ERRORES (MENSAJE, ORIGEN, ID_USUARIO)
        VALUES (P_MENSAJE, P_ORIGEN, P_ID_USUARIO);
    END;
	
END PKG_PROCEDIMIENTOS;

-- PAQUETE PARA ALMACENAR FUNCIONES
CREATE OR REPLACE PACKAGE PKG_FUNCIONES AS
    FUNCTION FN_NOMBRE_COMPLETO_USUARIO(P_ID_USUARIO IN NUMBER) RETURN VARCHAR2;
    FUNCTION FN_ESTADO_TEXTO_USUARIO(P_ID_USUARIO IN NUMBER) RETURN VARCHAR2;
    FUNCTION FN_TOTAL_USUARIOS_POR_ROL(P_ID_ROL IN NUMBER) RETURN NUMBER;
    FUNCTION FN_EXISTE_BENEFICIARIO(P_IDENTIFICACION IN VARCHAR2) RETURN NUMBER;
    FUNCTION FN_CONTAR_BENEFICIARIOS_NIVEL(P_ID_NIVEL IN NUMBER) RETURN NUMBER;
    FUNCTION FN_OBTENER_EDAD_BENEFICIARIO(P_ID_BENEFICIARIO IN NUMBER) RETURN NUMBER;
    FUNCTION FN_MATERIALES_DISPONIBLES_ASIGNATURA(P_ID_ASIGNATURA IN NUMBER) RETURN NUMBER;
    FUNCTION FN_CANTIDAD_PARTICIPACIONES_EVENTO(P_ID_EVENTO IN NUMBER) RETURN NUMBER;
END PKG_FUNCIONES;

CREATE OR REPLACE PACKAGE BODY PKG_FUNCIONES AS

    FUNCTION FN_NOMBRE_COMPLETO_USUARIO(P_ID_USUARIO IN NUMBER) RETURN VARCHAR2 IS
        V_QUERY VARCHAR2(1000);
        V_NOMBRE_COMPLETO VARCHAR2(150);
    BEGIN
        V_QUERY := 'SELECT NOMBRE || '' '' || APELLIDOS FROM TBL_USUARIOS WHERE ID_USUARIO = :1';
        EXECUTE IMMEDIATE V_QUERY INTO V_NOMBRE_COMPLETO USING P_ID_USUARIO;
        RETURN V_NOMBRE_COMPLETO;
    END;

    FUNCTION FN_ESTADO_TEXTO_USUARIO(P_ID_USUARIO IN NUMBER) RETURN VARCHAR2 IS
        V_ESTADO NUMBER;
    BEGIN
        SELECT ESTADO INTO V_ESTADO FROM TBL_USUARIOS WHERE ID_USUARIO = P_ID_USUARIO;
        RETURN CASE V_ESTADO WHEN 1 THEN 'Activo' ELSE 'Inactivo' END;
    END;

    FUNCTION FN_TOTAL_USUARIOS_POR_ROL(P_ID_ROL IN NUMBER) RETURN NUMBER IS
        V_CANTIDAD NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_CANTIDAD FROM TBL_USUARIOS WHERE ID_ROL = P_ID_ROL;
        RETURN V_CANTIDAD;
    END;

    FUNCTION FN_EXISTE_BENEFICIARIO(P_IDENTIFICACION IN VARCHAR2) RETURN NUMBER IS
        V_EXISTE NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_EXISTE FROM TBL_BENEFICIARIOS WHERE IDENTIFICACION = P_IDENTIFICACION;
        RETURN CASE WHEN V_EXISTE > 0 THEN 1 ELSE 0 END;
    END;

    FUNCTION FN_CONTAR_BENEFICIARIOS_NIVEL(P_ID_NIVEL IN NUMBER) RETURN NUMBER IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL FROM TBL_BENEFICIARIOS WHERE ID_NIVEL = P_ID_NIVEL;
        RETURN V_TOTAL;
    END;

    FUNCTION FN_OBTENER_EDAD_BENEFICIARIO(P_ID_BENEFICIARIO IN NUMBER) RETURN NUMBER IS
        V_FECHA_NAC DATE;
        V_EDAD NUMBER;
    BEGIN
        SELECT FECHA_NACIMIENTO INTO V_FECHA_NAC FROM TBL_BENEFICIARIOS WHERE ID_BENEFICIARIO = P_ID_BENEFICIARIO;
        V_EDAD := TRUNC(MONTHS_BETWEEN(SYSDATE, V_FECHA_NAC) / 12);
        RETURN V_EDAD;
    END;

    FUNCTION FN_MATERIALES_DISPONIBLES_ASIGNATURA(P_ID_ASIGNATURA IN NUMBER) RETURN NUMBER IS
        V_CANTIDAD NUMBER;
        V_SQL VARCHAR(1000);
    BEGIN
        V_SQL := 'SELECT COUNT(*) FROM TBL_MATERIALES WHERE ID_ASIGNATURA = :1 AND ESTADO = 1';
        EXECUTE IMMEDIATE V_SQL INTO V_CANTIDAD USING P_ID_ASIGNATURA;
        RETURN V_CANTIDAD;
    END;

    FUNCTION FN_CANTIDAD_PARTICIPACIONES_EVENTO(P_ID_EVENTO IN NUMBER) RETURN NUMBER IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL FROM TBL_PARTICIPACION_EVENTOS WHERE ID_EVENTO = P_ID_EVENTO;
        RETURN V_TOTAL;
    END;
	
END PKG_FUNCIONES;
