---------------------------------------------------------------------------------------------------------------
-------------------------------------------- CREACION DE TRIGGERS ---------------------------------------------
---------------------------------------------------------------------------------------------------------------

-- TRIGGER PARA VALIDAR QUE LOS BENEFICIARIOS TENGAN UNA EDAD MINIMA DE 0 AÑOS
CREATE OR REPLACE TRIGGER TRG_VALIDA_EDAD_BENEFICIARIO
BEFORE INSERT OR UPDATE ON TBL_BENEFICIARIOS
FOR EACH ROW
DECLARE	
	V_EDAD NUMBER;
BEGIN
	V_EDAD := TRUNC(MONTHS_BETWEEN(SYSDATE, :NEW.FECHA_NACIMIENTO) / 12);
	
	IF V_EDAD < 0 THEN
		RAISE_APPLICATION_ERROR(-20002, 'La fecha de nacimiento no puede estar en el futuro. ');
	END IF;
END;

-- TRIGGER PARA INSERTAR MENSAJE EN LA BITACORA CUANDO UN BENEFICIARIO ES MODIFICADO
CREATE OR REPLACE TRIGGER TRG_LOG_CAMBIOS_BENEFICIARIO
AFTER UPDATE ON TBL_BENEFICIARIOS
FOR EACH ROW
BEGIN
	INSERT INTO TBL_BITACORAS(ACCION, ID_USUARIO)
	VALUES ('Modificacion de beneficiario: ' || :OLD.NOMBRE || ' ' || :OLD.APELLIDOS, NULL);
END;

-- TRIGGER PARA ASIGNAR ESTADO DEL MATERIAL COMO ACTIVO SI NO SE ESPECIFICA
CREATE OR REPLACE TRIGGER TRG_ESTADO_MATERIAL
BEFORE INSERT ON TBL_MATERIALES
FOR EACH ROW
BEGIN
	IF :NEW.ESTADO IS NULL THEN
		:NEW.ESTADO := 1;
	END IF;
END;

-- TRIGGER PARA INSERTAR EVENTOS CON FECHA DE FINALIZACION IGUAL A LA DE INICIO
CREATE OR REPLACE TRIGGER TRG_VALIDAR_FECHA_EVENTO
BEFORE INSERT OR UPDATE ON TBL_EVENTOS
FOR EACH ROW
BEGIN 
	IF :NEW.FECHA_FIN < :NEW.FECHA_INICIO THEN
		RAISE_APPLICATION_ERROR(-20001, 'La fecha de finalizacion no puede ser anterior a la fecha de inicio. ');
	END IF;
END;

-- TRIGGER PARA NO ELIMINAR EVENTOS SI YA TIENEN BENEFICIARIOS INSCRITOS
CREATE OR REPLACE TRIGGER TRG_NO_BORRAR_EVENTO_CON_PARTICIPANTES
BEFORE DELETE ON TBL_EVENTOS
FOR EACH ROW
DECLARE
	V_CANTIDAD NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_CANTIDAD
	FROM TBL_PARTICIPACION_EVENTOS
	WHERE ID_EVENTO = :OLD.ID_EVENTO;
	
	IF V_CANTIDAD > 0 THEN
		RAISE_APPLICATION_ERROR(-20003, 'No se puede eliminar un evento con participantes registrados. ');
	END IF;
END;

-- TRIGGER PARA REGISTRAR BITACORA CUANDO UN USUARIO ES INSERTADO
CREATE OR REPLACE TRIGGER TRG_AUDIT_USUARIOS
AFTER INSERT OR UPDATE OR DELETE ON TBL_USUARIOS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO TBL_BITACORAS (ACCION, ID_USUARIO)
        VALUES ('INSERT', :NEW.ID_USUARIO);
        
    ELSIF UPDATING THEN
        INSERT INTO TBL_BITACORAS (ACCION, ID_USUARIO)
        VALUES ('UPDATE', :NEW.ID_USUARIO);
        
    ELSIF DELETING THEN
        INSERT INTO TBL_BITACORAS (ACCION, ID_USUARIO)
        VALUES ('DELETE', :OLD.ID_USUARIO);
    END IF;
END;

-- TRIGGER PARA AUTOREGISTRAR UN ERROR EN ALGUNA TABLA CRITICA
CREATE OR REPLACE TRIGGER TRG_AUTOREGISTRO_BITACORA_ERRORES
AFTER INSERT ON TBL_AUDITORIA_ERRORES
FOR EACH ROW
BEGIN
	INSERT INTO TBL_BITACORAS (ACCION, ID_USUARIO)
	VALUES (
		'Se registrÃ³ un error: ' || :NEW.MENSAJE || ' | Origen: ' || :NEW.ORIGEN,
		:NEW.ID_USUARIO
	);
END;

-- TRIGGER PARA IMRPIMIR MENSAJE CUANDO SE INSERTA UN NUEVO ERROR
CREATE OR REPLACE TRIGGER TRG_AUDIT_ERRORES
AFTER INSERT ON TBL_AUDITORIA_ERRORES
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('Error registrado: ' || :NEW.MENSAJE || ' | Origen: ' || :NEW.ORIGEN);
END;
