CREATE OR REPLACE TRIGGER TRG_VALIDAR_FECHA_EVENTO
BEFORE INSERT OR UPDATE ON TBL_EVENTOS
FOR EACH ROW
BEGIN 
	IF :NEW.FECHA_FIN < :NEW.FECHA_INICIO THEN
		RAISE_APPLICATION_ERROR(-20001, 'La fecha de finalizacion no puede ser anterior a la fecha de inicio. ');
	END IF;
END;
