CREATE OR REPLACE TRIGGER TRG_AUDIT_USUARIOS
AFTER INSERT OR UPDATE OR DELETE ON TBL_USUARIOS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO TBL_BITACORAS (ACCION, ID_USUARIO)
        VALUES ('INSERT', :NEW.ID_USUARIO);
        
    ELSIF UPDATING THEN
        INSERT INTO TBL_BITACORAS (ACCION, ID_USUARIO)
        VALUES ('UPDATE', :NEW.ID_USUARIO);
        
    ELSIF DELETING THEN
        INSERT INTO TBL_BITACORAS (ACCION, ID_USUARIO)
        VALUES ('DELETE', :OLD.ID_USUARIO);
    END IF;
END;
