CREATE OR REPLACE TRIGGER TRG_NO_BORRAR_EVENTO_CON_PARTICIPANTES
BEFORE DELETE ON TBL_EVENTOS
FOR EACH ROW
DECLARE
	V_CANTIDAD NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_CANTIDAD
	FROM TBL_PARTICIPACION_EVENTOS
	WHERE ID_EVENTO = :OLD.ID_EVENTO;
	
	IF V_CANTIDAD > 0 THEN
		RAISE_APPLICATION_ERROR(-20003, 'No se puede eliminar un evento con participantes registrados. ');
	END IF;
END;
