CREATE OR REPLACE TRIGGER TRG_LOG_CAMBIOS_BENEFICIARIO
AFTER UPDATE ON TBL_BENEFICIARIOS
FOR EACH ROW
BEGIN
	INSERT INTO TBL_BITACORAS(ACCION, ID_USUARIO)
	VALUES ('Modificacion de beneficiario: ' || :OLD.NOMBRE || ' ' || :OLD.APELLIDOS, NULL);
END;
