CREATE OR REPLACE TRIGGER TRG_VALIDA_EDAD_BENEFICIARIO
BEFORE INSERT OR UPDATE ON TBL_BENEFICIARIOS
FOR EACH ROW
DECLARE	
	V_EDAD NUMBER;
BEGIN
	V_EDAD := TRUNC(MONTHS_BETWEEN(SYSDATE, :NEW.FECHA_NACIMIENTO) / 12);
	
	IF V_EDAD < 0 THEN
		RAISE_APPLICATION_ERROR(-20002, 'La fecha de nacimiento no puede estar en el futuro. ');
	END IF;
END;
