CREATE OR REPLACE FUNCTION FN_CONTAR_BENEFICIARIOS_NIVEL (
	P_ID_NIVEL IN NUMBER
) RETURN NUMBER IS
	V_TOTAL NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_TOTAL
	FROM TBL_BENEFICIARIOS
	WHERE ID_NIVEL = P_ID_NIVEL;
	
	RETURN V_TOTAL;
END;
