CREATE OR REPLACE FUNCTION FN_CANTIDAD_PARTICIPACIONES_EVENTO (
	P_ID_EVENTO IN NUMBER
) RETURN NUMBER IS
	V_TOTAL NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_TOTAL
	FROM TBL_PARTICIPACION_EVENTOS
	WHERE ID_EVENTO = P_ID_EVENTO;
	
	RETURN V_TOTAL;
END;
