CREATE OR REPLACE FUNCTION FN_EXISTE_BENEFICIARIO (
	P_IDENTIFICACION IN VARCHAR2
) RETURN NUMBER IS
	V_EXISTE NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_EXISTE
	FROM TBL_BENEFICIARIOS
	WHERE IDENTIFICACION = P_IDENTIFICACION;
	
	RETURN CASE WHEN V_EXISTE > 0 THEN 1 ELSE 0
	END;
END;
