CREATE OR REPLACE FUNCTION FN_ESTADO_TEXTO_USUARIO (
	P_ID_USUARIO IN NUMBER
) RETURN VARCHAR2 IS
	V_ESTADO NUMBER;
BEGIN
	SELECT ESTADO INTO V_ESTADO
	FROM TBL_USUARIOS
	WHERE ID_USUARIO = P_ID_USUARIO;
	
	RETURN CASE V_ESTADO WHEN 1 THEN 'Activo' ELSE 'Inactivo'
	END;
END;
