CREATE OR REPLACE FUNCTION FN_MATERIALES_DISPONIBLES_ASIGNATURA (
	P_ID_ASIGNATURA IN NUMBER
) RETURN NUMBER IS
	V_CANTIDAD NUMBER;
	V_SQL VARCHAR(1000);
BEGIN
	V_SQL := 'SELECT COUNT(*) FROM TBL_MATERIALES WHERE ID_ASIGNATURA = :1 AND ESTADO = 1';
	
	EXECUTE IMMEDIATE V_SQL INTO V_CANTIDAD USING P_ID_ASIGNATURA;
	
	RETURN V_CANTIDAD;
END;
