CREATE OR REPLACE FUNCTION FN_OBTENER_EDAD_BENEFICIARIO (
	P_ID_BENEFICIARIO IN NUMBER
) RETURN NUMBER IS
	V_FECHA_NAC DATE;
	V_EDAD NUMBER;
BEGIN
	SELECT FECHA_NACIMIENTO INTO V_FECHA_NAC
	FROM TBL_BENEFICIARIOS
	WHERE ID_BENEFICIARIO = P_ID_BENEFICIARIO;
	
	V_EDAD := TRUNC(MONTHS_BETWEEN(SYSDATE, V_FECHA_NAC) / 12);
	RETURN V_EDAD;
END;
