CREATE OR REPLACE FUNCTION FN_TOTAL_USUARIOS_POR_ROL (
	P_ID_ROL IN NUMBER
) RETURN NUMBER IS
	V_CANTIDAD NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_CANTIDAD
	FROM TBL_USUARIOS
	WHERE ID_ROL = P_ID_ROL;
	
	RETURN V_CANTIDAD;
END;
