----------------------------------------------------------------------------------------------------------------
-------------------------------------------- CREACION DE FUNCIONES ---------------------------------------------
----------------------------------------------------------------------------------------------------------------

-- FUNCION PARA OBTENER NOMBRE COMPLETO DE USUARIO POR ID
CREATE OR REPLACE FUNCTION FN_NOMBRE_COMPLETO_USUARIO (
	P_ID_USUARIO IN NUMBER
) RETURN VARCHAR2 IS
	V_QUERY VARCHAR2(1000);
	V_NOMBRE_COMPLETO VARCHAR2(150);
BEGIN
	V_QUERY := 'SELECT NOMBRE || '' '' || APELLIDOS FROM TBL_USUARIOS WHERE ID_USUARIO = :1';
	
	EXECUTE IMMEDIATE V_QUERY INTO V_NOMBRE_COMPLETO USING P_ID_USUARIO;
	
	RETURN V_NOMBRE_COMPLETO;
END;

-- FUNCION PARA CONVERTIR ESTADO DE UN USUARIO
CREATE OR REPLACE FUNCTION FN_ESTADO_TEXTO_USUARIO (
	P_ID_USUARIO IN NUMBER
) RETURN VARCHAR2 IS
	V_ESTADO NUMBER;
BEGIN
	SELECT ESTADO INTO V_ESTADO
	FROM TBL_USUARIOS
	WHERE ID_USUARIO = P_ID_USUARIO;
	
	RETURN CASE V_ESTADO WHEN 1 THEN 'Activo' ELSE 'Inactivo'
	END;
END;

-- FUNCION PARA CONTAR USUARIOS POR ROL
CREATE OR REPLACE FUNCTION FN_TOTAL_USUARIOS_POR_ROL (
	P_ID_ROL IN NUMBER
) RETURN NUMBER IS
	V_CANTIDAD NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_CANTIDAD
	FROM TBL_USUARIOS
	WHERE ID_ROL = P_ID_ROL;
	
	RETURN V_CANTIDAD;
END;

-- FUNCION PARA VERIFICAR EXISTENCIA DE UN BENEFICIARIO SEGUN IDENTIFICACION
CREATE OR REPLACE FUNCTION FN_EXISTE_BENEFICIARIO (
	P_IDENTIFICACION IN VARCHAR2
) RETURN NUMBER IS
	V_EXISTE NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_EXISTE
	FROM TBL_BENEFICIARIOS
	WHERE IDENTIFICACION = P_IDENTIFICACION;
	
	RETURN CASE WHEN V_EXISTE > 0 THEN 1 ELSE 0
	END;
END;

-- FUNCION PARA CONTAR BENEFICIARIOS ASIGNADOS A UN NIVEL
CREATE OR REPLACE FUNCTION FN_CONTAR_BENEFICIARIOS_NIVEL (
	P_ID_NIVEL IN NUMBER
) RETURN NUMBER IS
	V_TOTAL NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_TOTAL
	FROM TBL_BENEFICIARIOS
	WHERE ID_NIVEL = P_ID_NIVEL;
	
	RETURN V_TOTAL;
END;

-- FUNCION PARA OBTENER EDAD DE BENEFICIARIO
CREATE OR REPLACE FUNCTION FN_OBTENER_EDAD_BENEFICIARIO (
	P_ID_BENEFICIARIO IN NUMBER
) RETURN NUMBER IS
	V_FECHA_NAC DATE;
	V_EDAD NUMBER;
BEGIN
	SELECT FECHA_NACIMIENTO INTO V_FECHA_NAC
	FROM TBL_BENEFICIARIOS
	WHERE ID_BENEFICIARIO = P_ID_BENEFICIARIO;
	
	V_EDAD := TRUNC(MONTHS_BETWEEN(SYSDATE, V_FECHA_NAC) / 12);
	RETURN V_EDAD;
END;

-- FUNCION PARA CALCULAR CANTIDAD TOTAL DE MATERIALES ACTIVOS POR ASIGNATURA
CREATE OR REPLACE FUNCTION FN_MATERIALES_DISPONIBLES_ASIGNATURA (
	P_ID_ASIGNATURA IN NUMBER
) RETURN NUMBER IS
	V_CANTIDAD NUMBER;
	V_SQL VARCHAR(1000);
BEGIN
	V_SQL := 'SELECT COUNT(*) FROM TBL_MATERIALES WHERE ID_ASIGNATURA = :1 AND ESTADO = 1';
	
	EXECUTE IMMEDIATE V_SQL INTO V_CANTIDAD USING P_ID_ASIGNATURA;
	
	RETURN V_CANTIDAD;
END;

-- FUNCION PARA CANTIDAD DE BENEFICIARIOS PARTICIPANDO EN UN EVENTO
CREATE OR REPLACE FUNCTION FN_CANTIDAD_PARTICIPACIONES_EVENTO (
	P_ID_EVENTO IN NUMBER
) RETURN NUMBER IS
	V_TOTAL NUMBER;
BEGIN
	SELECT COUNT(*) INTO V_TOTAL
	FROM TBL_PARTICIPACION_EVENTOS
	WHERE ID_EVENTO = P_ID_EVENTO;
	
	RETURN V_TOTAL;
END;
