-----------------------------------------------------------------------------------------------------------------
-------------------------------------------- CREACION DE SECUENCIAS ---------------------------------------------
-----------------------------------------------------------------------------------------------------------------

-- SECUENCIA PARA ROLES
CREATE SEQUENCE SEQ_ROLES
START WITH 1
INCREMENT BY 1;

-- SECUENCIA PARA USUARIOS
CREATE SEQUENCE SEQ_USUARIOS
START WITH 1
INCREMENT BY 1;

-- SECUENCIA PARA BENEFICIARIOS
CREATE SEQUENCE SEQ_BENEFICIARIOS
START WITH 1
INCREMENT BY 1;

-- SECUENCIA PARA PROFESORES
CREATE SEQUENCE SEQ_PROFESORES
START WITH 1
INCREMENT BY 1;

-- SECUENCIA PARA NIVELES
CREATE SEQUENCE SEQ_NIVELES
START WITH 1
INCREMENT BY 1;

-- SECUENCIA PARA ASIGNATURAS
CREATE SEQUENCE SEQ_ASIGNATURAS 
START WITH 1
INCREMENT BY 1;

-- SECUENCIA PARA MATERIALES
CREATE SEQUENCE SEQ_MATERIALES
START WITH 1
INCREMENT BY 1;

-- SECUENCIA PARA EVENTOS
CREATE SEQUENCE SEQ_EVENTOS
START WITH 1
INCREMENT BY 1;

-- SECUENCIA PARA BITACORAS
CREATE SEQUENCE SEQ_BITACORAS
START WITH 1
INCREMENT BY 1;

-- SECUENCIA PARA AUDITORIA DE ERRORES
CREATE SEQUENCE SEQ_AUDITORIA_ERRORES
START WITH 1
INCREMENT BY 1;
