CREATE TABLE TBL_PARTICIPACION_EVENTOS (
	ID_EVENTO NUMBER,
	ID_BENEFICIARIO NUMBER,
	CONSTRAINT PK_PARTICIPACION PRIMARY KEY (ID_EVENTO, ID_BENEFICIARIO),
	CONSTRAINT FK_PARTICIPACION_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES TBL_EVENTOS(ID_EVENTO),
	CONSTRAINT FK_PARTICIPACION_BENEFICIARIO FOREIGN KEY (ID_BENEFICIARIO) REFERENCES TBL_BENEFICIARIOS(ID_BENEFICIARIO)
);
