CREATE OR REPLACE PROCEDURE SP_AGREGAR_USUARIO (
	P_IDENTIFICACION IN VARCHAR2,
	P_NOMBRE IN VARCHAR2,
	P_APELLIDOS IN VARCHAR2,
	P_CORREO IN VARCHAR2,
	P_CONTRASENNA IN VARCHAR2,
	P_ID_ROL IN NUMBER
) AS
BEGIN
	INSERT INTO TBL_USUARIOS (
		IDENTIFICACION, NOMBRE, APELLIDOS, CORREO, CONTRASENNA, ESTADO, ID_ROL
	)
	VALUES (
		P_IDENTIFICACION, P_NOMBRE, P_APELLIDOS, P_CORREO, P_CONTRASENNA, 1, P_ID_ROL
	);
END;
