CREATE OR REPLACE PROCEDURE SP_ELIMINAR_PARTICIPACION_EVENTO (
	P_ID_EVENTO IN NUMBER,
	P_ID_BENEFICIARIO IN NUMBER
) AS
BEGIN
	DELETE FROM TBL_PARTICIPACION_EVENTOS
	WHERE ID_EVENTO = P_ID_EVENTO AND ID_BENEFICIARIO = P_ID_BENEFICIARIO;
END;
