CREATE OR REPLACE PROCEDURE SP_INSERTAR_EVENTO (
	P_NOMBRE IN VARCHAR2,
	P_FECHA_INICIO IN DATE,
	P_FECHA_FIN IN DATE,
	P_DESCRIPCION IN VARCHAR2,
	P_RUTA_IMAGEN IN VARCHAR2
) AS
BEGIN
	INSERT INTO TBL_EVENTOS (NOMBRE, FECHA_INICIO, FECHA_FIN, DESCRIPCION, RUTA_IMAGEN)
	VALUES (P_NOMBRE, P_FECHA_INICIO, P_FECHA_FIN, P_DESCRIPCION, P_RUTA_IMAGEN);
END;
