CREATE OR REPLACE PROCEDURE SP_LISTAR_BENEFICIARIOS_NIVEL (
	P_ID_NIVEL IN NUMBER
) AS
	CURSOR C_BENEFICIARIO IS
		SELECT NOMBRE, APELLIDOS, IDENTIFICACION
		FROM TBL_BENEFICIARIOS
		WHERE ID_NIVEL = P_ID_NIVEL;
	
	V_NOMBRE TBL_BENEFICIARIOS.NOMBRE%TYPE;
	V_APELLIDOS TBL_BENEFICIARIOS.APELLIDOS%TYPE;
	V_IDENTIFICACION TBL_BENEFICIARIOS.IDENTIFICACION%TYPE;
BEGIN
	OPEN C_BENEFICIARIO;
	LOOP
		FETCH C_BENEFICIARIO INTO V_NOMBRE, V_APELLIDOS, V_IDENTIFICACION;
		EXIT WHEN C_BENEFICIARIO%NOTFOUND;
		
		DBMS_OUTPUT.PUT_LINE('Beneficiario: ' || V_NOMBRE || ' ' || V_APELLIDOS || ' - ID: ' || V_IDENTIFICACION);
	END LOOP;
	CLOSE C_BENEFICIARIO;
END;
