CREATE OR REPLACE PROCEDURE SP_LISTAR_PROFESORES_CON_TITULOS (
	P_MIN_TITULOS IN NUMBER
) AS
	CURSOR C_PROFESOR IS
		SELECT NOMBRE, APELLIDOS, CANTIDAD_TITULOS
		FROM TBL_PROFESORES
		WHERE CANTIDAD_TITULOS >= P_MIN_TITULOS;
		
	V_NOMBRE TBL_PROFESORES.NOMBRE%TYPE;
	V_APELLIDOS TBL_PROFESORES.APELLIDOS%TYPE;
	V_TITULOS TBL_PROFESORES.CANTIDAD_TITULOS%TYPE;
BEGIN
	OPEN C_PROFESOR;
	LOOP
		FETCH C_PROFESOR INTO V_NOMBRE, V_APELLIDOS, V_TITULOS;
		EXIT WHEN C_PROFESOR%NOTFOUND;
		
		DBMS_OUTPUT.PUT_LINE('Porfesor: ' || V_NOMBRE || ' ' || V_APELLIDOS || ' | Titulos: ' || V_TITULOS);
	END LOOP;
	CLOSE C_PROFESOR;
END;
