CREATE OR REPLACE PROCEDURE SP_LISTAR_MATERIALES_ASIGNATURA (
	P_ID_ASIGNATURA IN NUMBER
) AS
	CURSOR C_MATERIAL IS
		SELECT M.NOMBRE, M.TIPO, M.CANTIDAD, M.ESTADO
		FROM TBL_MATERIALES M
		WHERE M.ID_ASIGNATURA = P_ID_ASIGNATURA;
	
	V_NOMBRE TBL_MATERIALES.NOMBRE%TYPE;
	V_TIPO TBL_MATERIALES.TIPO%TYPE;
	V_CANTIDAD TBL_MATERIALES.CANTIDAD%TYPE;
	V_ESTADO TBL_MATERIALES.ESTADO%TYPE;
BEGIN
	OPEN C_MATERIAL;
	LOOP
		FETCH C_MATERIAL INTO V_NOMBRE, V_TIPO, V_CANTIDAD, V_ESTADO;
		EXIT WHEN C_MATERIAL%NOTFOUND;
		
		DBMS_OUTPUT.PUT_LINE('Material: ' || V_NOMBRE || ' | Tipo: ' || V_TIPO || ' | Cantidad: ' || V_CANTIDAD || ' | Estado: ' || V_ESTADO);
	END LOOP;
	CLOSE C_MATERIAL;
END;
