CREATE OR REPLACE PROCEDURE SP_REGISTRAR_PARTICIPACION (
	P_ID_EVENTO IN NUMBER,
	P_ID_BENEFICIARIO IN NUMBER
) AS
BEGIN
	INSERT INTO TBL_PARTICIPACION_EVENTOS (ID_EVENTO, ID_BENEFICIARIO)
	VALUES (P_ID_EVENTO, P_ID_BENEFICIARIO);
END;
