CREATE OR REPLACE PROCEDURE SP_VER_BITACORA_USUARIOS IS
	V_ROW TBL_BITACORAS%ROWTYPE;
	CURSOR C_BITACORA IS
		SELECT * FROM TBL_BITACORAS;
BEGIN
	OPEN C_BITACORA;
	LOOP
		FETCH C_BITACORA INTO V_ROW;
		EXIT WHEN C_BITACORA%NOTFOUND;
		
		DBMS_OUTPUT.PUT_LINE('[' || V_ROW.FECHA_HORA || '] Usuario: ' || V_ROW.ID_USUARIO || ' realizo una accion: ' || V_ROW.ACCION);
	END LOOP;
	CLOSE C_BITACORA;
END;
